### ISSUE TITLE
COMPILED/COMPILED

### ISSUE THREAD

**Issue by kakulukia** [andreyfedoseev/django-static-precompiler#95] opened 2016-10-10 14:21 UTC
with kinda the default configuration i get a wrong paths in the generated css file

/*# sourceMappingURL=../COMPILED/sass/styles.css.map */

being in the sass folder this results in the following URL:
/static/COMPILED/COMPILED/sass/styles.css.map HTTP/1.1" 404 1825 which obviously aint there

My settings are:

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'static_precompiler.finders.StaticPrecompilerFinder',
]

STATIC_PRECOMPILER_COMPILERS = (
    ('static_precompiler.compilers.libsass.SCSS', {
        "sourcemap_enabled": True,
    }),
    ('static_precompiler.compilers.libsass.SASS', {
        "sourcemap_enabled": True,
    }),
)

Whats wrong here?

**Comment by kakulukia** [comment] 2016-10-10 14:29
i also noticed that with a collected static file in place and debug set to True, recent changes to the source file will be ignored and not compiled on the fly. Removing the collected, old version of the sass file reactivated the live compiling :/

**Comment by kavdev** [comment] 2017-04-21 15:50
Seeing the same issues; same setup

**Comment by kavdev** [comment] 2017-04-21 15:52
@andreyfedoseev I have some time next week to work on this; let me know if you have an idea of what might be causing this. Also let me know if you need any debug data.

**Comment by kakulukia** [comment] 2017-04-21 16:15
Sadly I can't remember what happened half a year ago other than what's written down here. Didn't continue working on that project since then.

**Comment by gabrielelucci** [comment] 2021-04-18 13:18
I can confirm that the bug is still here. The generated `sourceMappingURL` is wrong.

I'm also using `libsass` compiler and didn't test other compilers, perhaps the issue is only related to `libsass` compiler.

**Comment by andreyfedoseev** [comment] 2022-11-14 05:38
This should be fixed now, the fix released in 2.3

**Closed** 2022-11-14 05:40 UTC
Labels: bug

**Comment by kavdev** [comment] 2022-11-15 07:26
Woah, what a throwback 😃 Congrats on the release!
