### ISSUE TITLE
Add Dart Sass support 

### ISSUE THREAD

**Issue by Kasperror** [andreyfedoseev/django-static-precompiler#146] opened 2022-04-05 11:46 UTC
Might be a huge improvement and a rebirth to this package since Dart Sass is now the official version. I haven't done enough research but it actually might come down to defining cli interface mapping from the current one.

Can create PR but in the future cuz as for now im just a Sass beginner. 

For anyone who just wants to use basic compilation using Dart Sass, removing 
`
  "--sourcemap={0}".format("auto" if self.is_sourcemap_enabled else "none"),
`
scss.py /74

seems to solve the problem with StaticCompilerError

**Comment by andreyfedoseev** [comment] 2022-11-14 05:49
Duplicate of #148 

I'm closing this one as a duplicate, even though it was submitted earlier.

**Closed by andreyfedoseev** 2022-11-14 05:49 UTC
